RESOURCES = [
    {"name": "cliente", "kind": "fact"},
    {"name": "linea-servicio", "kind": "fact", "always_paginate": True},
    {"name": "contrato", "kind": "fact", "always_paginate": True},
    {"name": "preventa", "kind": "fact"},
    {"name": "solicitud-servicio", "kind": "fact"},
    {"name": "prospecto", "kind": "fact"},
    {"name": "encuesta-prospecto", "kind": "fact"},
    {"name": "consulta-buro", "kind": "fact"},
    {"name": "sistema-referidos", "kind": "fact"},
    {"name": "trazabilidad-venta", "kind": "fact"},
    {"name": "agendamiento", "kind": "fact"},
    {"name": "orden-trabajo", "kind": "fact", "always_paginate": True},
    {"name": "ticket-tecnico", "kind": "fact"},
    {"name": "transaccion", "kind": "fact", "always_paginate": True},
    {"name": "alquiler", "kind": "fact"},
    {"name": "usuario", "kind": "dimension"},
    {"name": "canal-venta", "kind": "dimension"},
    {"name": "motivo-rechazo", "kind": "dimension"},
    {"name": "metodo-pago", "kind": "dimension"},
    {"name": "ciudad", "kind": "dimension"},
    {"name": "zona", "kind": "dimension"},
    {"name": "sector", "kind": "dimension"},
    {"name": "config-plantilla-cliente", "kind": "dimension"},
    {"name": "plan-internet", "kind": "dimension"},
    {"name": "producto", "kind": "dimension"},
    {"name": "nodo", "kind": "dimension"},
    {"name": "nap", "kind": "dimension"},
    {"name": "nap-primaria", "kind": "dimension"},
    {"name": "asunto-ticket", "kind": "dimension"},
]

RESOURCE_NAMES = {resource["name"] for resource in RESOURCES}
