# Generated by Codex

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En ejecucion"),
                            ("success", "Correcta"),
                            ("failed", "Fallida"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("total_created", models.PositiveIntegerField(default=0)),
                ("total_updated", models.PositiveIntegerField(default=0)),
                ("total_deleted", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="WarehouseRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resource", models.CharField(db_index=True, max_length=80)),
                ("resource_kind", models.CharField(db_index=True, max_length=20)),
                ("external_id", models.CharField(db_index=True, max_length=120)),
                ("raw_data", models.JSONField()),
                ("normalized_data", models.JSONField()),
                ("row_hash", models.CharField(db_index=True, max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "last_sync",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="warehouse.syncrun",
                    ),
                ),
            ],
            options={
                "ordering": ["resource", "external_id"],
                "indexes": [
                    models.Index(fields=["resource", "is_active"], name="warehouse_w_resource_b38f9c_idx"),
                    models.Index(fields=["resource_kind", "is_active"], name="warehouse_w_resource_49f112_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("resource", "external_id"), name="uniq_resource_external_id")
                ],
            },
        ),
    ]
